[package]
name = "audisp-plugin"
version = "0.1.0"
edition = "2021"
authors = ["CÃ´me VINCENT <come.vincent@polytechnique.edu>"]
license = "GPL-3.0"
description = "audisp plugin for tiny-jail"

[dependencies]

[[bin]]
name = "audisp-plugin"
path = "src/main.rs"
